import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import Shell from "@/components/Shell";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full">
        <Shell>{children}</Shell>
      </body>
    </html>
  );
}
